### ISSUE TITLE
Not padding and margin

### ISSUE THREAD

**Issue by anay-208** [yxthaarth/sharlz#1]
There needs to be padding and margin top in the website.
![image](https://github.com/Kirito-Blacksword/sharlz/assets/96932471/e1b0a14d-bb9e-4eaf-b585-cc5f9acb6b9d)

**Comment by yxthaarth** [comment]
fixed

**Comment by yxthaarth** [comment]
![image](https://github.com/Kirito-Blacksword/sharlz/assets/89380515/c14ace59-410d-41ff-bc94-abcb9078ebae)
this right?

**Comment by anay-208** [comment]
I've sent a screenshot. Kindly check that. There needs to be spacing between components

**Comment by yxthaarth** [comment]
> I've sent a screenshot. Kindly check that. There needs to be spacing between components

![image](https://github.com/Kirito-Blacksword/sharlz/assets/89380515/39ec8173-294b-4d43-8437-596b4dc6e755)
fine now?

**Comment by anay-208** [comment]
Commit the changes, I'll view in the web app

**Comment by anay-208** [comment]
Why is it their in rows in web app.
You can see the preview from https://sharlz.com/
and https://sharlz.com/products.

The components are taken from there only
